# Generated by Django 6.1 on 2026-08-11 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('contact_info', models.CharField(max_length=120, verbose_name='Email ou WhatsApp')),
                ('product_interest', models.CharField(blank=True, max_length=200, verbose_name='Peça de interesse')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('handled', models.BooleanField(default=False, verbose_name='Já respondido')),
            ],
            options={
                'verbose_name': 'Pedido de contacto',
                'verbose_name_plural': 'Pedidos de contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Vaso geométrico', max_length=200, verbose_name='Nome do produto')),
                ('slug', models.SlugField(blank=True, help_text='Preenchido automaticamente a partir do nome. Não precisas de mexer aqui.', max_length=220, unique=True)),
                ('category', models.CharField(choices=[('digital', 'Ficheiro digital (download)'), ('physical', 'Peça impressa (enviada por correio)')], default='physical', max_length=10, verbose_name='Tipo de produto')),
                ('short_description', models.CharField(blank=True, help_text='Uma frase curta que aparece no cartão do catálogo (opcional).', max_length=160, verbose_name='Descrição curta')),
                ('description', models.TextField(blank=True, help_text='Texto mais longo, mostrado quando o cliente abre a janela de detalhes.', verbose_name='Descrição completa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço (€)')),
                ('price_note', models.CharField(blank=True, help_text='Ex: "desde", para mostrar "desde 10,50 €". Deixa em branco se não for preciso.', max_length=40, verbose_name='Nota de preço')),
                ('print_time', models.CharField(blank=True, help_text='Só para ficheiros digitais. Ex: "4h30".', max_length=40, verbose_name='Tempo de impressão')),
                ('weight', models.CharField(blank=True, help_text='Só para ficheiros digitais. Ex: "68g".', max_length=40, verbose_name='Peso')),
                ('digital_file', models.FileField(blank=True, help_text='Só para ficheiros digitais. O ficheiro STL/3MF que o cliente vai descarregar.', null=True, upload_to='digital_files/', verbose_name='Ficheiro para download')),
                ('material', models.CharField(blank=True, help_text='Só para peças impressas. Ex: "PLA", "PETG".', max_length=60, verbose_name='Material')),
                ('lead_time', models.CharField(blank=True, help_text='Só para peças impressas. Ex: "3-5 dias".', max_length=60, verbose_name='Prazo de entrega')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarca para esconder o produto do site sem o apagar.', verbose_name='Visível no site')),
                ('order', models.PositiveIntegerField(default=0, help_text='Produtos com número mais baixo aparecem primeiro no catálogo.', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, help_text='A foto com número mais baixo aparece primeiro (é a foto principal).', verbose_name='Ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Foto do produto',
                'verbose_name_plural': 'Fotos do produto',
                'ordering': ['order', 'id'],
            },
        ),
    ]
